apiVersion: v1
kind: Secret
metadata:
  name: authentication-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=db;Database=AuthDb;User Id=sa;Password=String@1234;TrustServerCertificate=true;"
  JwtSettings__Secret: "SuperSecretKeyThatIsLongEnoughjsjkasasjsaksajkaskjskj"
  RABBITMQ_DEFAULT_PASS: "dev_password"
  REDIS_PASSWORD: "dev_user"
